spring:
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:my_db
  jpa:
    hibernate:
      ddl-auto: create-drop